package hash_table;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;

/**
 * @author gaoshuo
 * @description
 *
 * Given two strings s and t which consist of only lowercase letters.
 *
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 * Find the letter that was added in t.
 *
 * Example:
 *
 * Input:
 * s = "abcd"
 * t = "abcde"
 *
 * Output:
 * e
 *
 * Explanation:
 * 'e' is the letter that was added.
 *
 * @date 2019-02-27
 */
public class FindTheDifference {

    public static void main(String[] args) {
        System.out.println(findTheDifference("abcde", "abcdee"));
    }

    private static char findTheDifference(String s, String t) {
        int sums = 0;
        int sumt = 0;

        for (char a: s.toCharArray()) {
            sums += (a - 'a');
        }
        for (char b: t.toCharArray()) {
            sumt += (b - 'a');
        }

        return (char)(sumt - sums  +97);
     }

//    private static char findTheDifference(String s, String t) {
//       char[] schars = s.toCharArray();
//       char[] tchars = t.toCharArray();
//
//        List<Character> list = new ArrayList<>();
//
//        for (Character character : tchars) {
//            list.add(character);
//        }
//
//        for (Character character : schars) {
//            list.remove(character);
//        }
//
//        return list.get(0);
//    }
}
